title: DM's blog
author: zmj
email: zdm0814@gmail.com
description: zmj's Self-learning IT blog
# social links
# juejin_username: 传达室老大爷 
# github_username:  hotbloodyoungman 
show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
